from __future__ import annotations

from ui.alarm.definitions import AlarmDefinition, AlarmTone
from ui.alarm.mappers import map_alarm_group

DEFINITIONS: tuple[AlarmDefinition, ...] = (
    AlarmDefinition(
        id='----',
        occurrence='-----',
        name='',
        title='MP10',
        cause='218 / 300 µg/m³ sobre 70% del límite',
        risk_category='Impacto',
        business_category='Medio Ambiente',
        risk_level='C3',
        tone=AlarmTone.DANGER,
        activity_time='5',
        activity_time_unit='m',
        order=1,
        group='',
    ),
    AlarmDefinition(
        id='----',
        occurrence='-----',
        name='',
        title='MP10',
        cause='218 / 300 µg/m³ sobre 70% del límite',
        risk_category='Impacto',
        business_category='Seguridad y Salud',
        risk_level='C2',
        tone=AlarmTone.WARNING,
        activity_time='10',
        activity_time_unit='m',
        order=1,
        group='',
    ),
    AlarmDefinition(
        id='----',
        occurrence='-----',
        name='',
        title='PH',
        cause='Nivel bajo',
        risk_category='Riesgo',
        business_category='Productividad',
        risk_level='C2',
        tone=AlarmTone.WARNING,
        activity_time='1',
        activity_time_unit='h',
        order=2,
        group='',
    ),
    AlarmDefinition(
        id='----',
        occurrence='-----',
        name='',
        title='CH-1',
        cause='F/S',
        risk_category='Impacto',
        business_category='Costos',
        risk_level='C1',
        tone=AlarmTone.DANGER,
        activity_time='55',
        activity_time_unit='m',
        order=2,
        group='',
    ),
    AlarmDefinition(
        id='----',
        occurrence='-----',
        name='',
        title='TK-202',
        cause='Nivel alto - rebose',
        risk_category='Impacto',
        business_category='Costos',
        risk_level='C1',
        tone=AlarmTone.DANGER,
        activity_time='4',
        activity_time_unit='h',
        order=2,
        group='',
    ),
    AlarmDefinition(
        id='----',
        occurrence='-----',
        name='',
        title='TEST-TITLE-LARGE'*20,
        cause='TEST-CAUSE-LARGE'*30,
        risk_category='Impacto',
        business_category='Costos',
        risk_level='C1',
        tone=AlarmTone.DANGER,
        activity_time='2',
        activity_time_unit='d',
        order=2,
        group='',
    ),
)

alarms = map_alarm_group(
    definitions=DEFINITIONS,
).to_component()

